AllCops:
  NewCops: enable
  Exclude:
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'bin/{rails,rake,bundle}'
    - 'db/**/*'

Layout/LineLength:
  Max: 160

Metrics/BlockLength:
  Exclude:
    - 'config/routes.rb'
    - 'spec/**/*'

Metrics/MethodLength:
  Exclude:
    - 'app/queries/*'
    - 'app/controllers/graphql_controller.rb'

Naming/MethodParameterName:
  Exclude:
    - 'app/controllers/graphql_controller.rb'

Naming/PredicateName:
  Enabled: false

Naming/VariableNumber:
  EnforcedStyle: snake_case

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
